// import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import { Sunflower } from 'next/font/google';

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
const sunflower = Sunflower({
  weight: ['300', '500', '700'],  // You can choose which weights to include
  subsets: ['latin'],
  display: 'swap',
});


export const metadata = {
  title: "Move Around",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sunflower.className}  bg-[#FFFCF9] text-black antialiased`}
      >
      <Header />
        {children}
      </body>
    </html>
  );
}
