// import localFont from "next/font/local";
import Footer from "@/components/Footer";
import "./globals.css";
import Header from "@/components/Header";

import { Toaster } from "react-hot-toast";
import axios from "axios";
import { cookies } from "next/headers";
import jwt from "jsonwebtoken";
import SessionWrapper from "@/components/SessionWrapper";
import { useSession } from "next-auth/react";
import "leaflet/dist/leaflet.css";
import { FormProvider } from "@/context/FormContext";
import { UserDataProvider } from "@/context/UserDataContext.js";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Move Around",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();
  const token = cookieStore.get("token")?.value;

  // console.log(`token : ${token}`);

  const data = jwt.decode(token);

  let userData = null;

  const fetchUserData = async () => {
    try {
      const response = await fetch(
        `${process.env.NEXT_PUBLIC_API_URL}/api/user/details`,
        {
          method: "POST", // Use POST method
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ userId: data?.id }), // Send userId in the request body
        }
      );

      if (!response.ok) {
        throw new Error("Failed to fetch user data");
      }

      // console.log(response);

      const dataOfUser = await response.json(); // Parse the JSON response
      // console.log(dataOfUser);

      console.log("data fetched successfully");
      return dataOfUser.data;
    } catch (error) {
      console.error("Error fetching user data:", error);
      return null; // Return null in case of an error
    }
  };

  userData = await fetchUserData();

  console.log("hi");

  // console.log(userData);

  // console.log(`token data: ${data}`);

  // const cookieStored = cookies();
  //   const tokend = cookieStored.get('next-auth.session-token')?.value;

  //   // Decode the token to get user data
  //   const decoded = jwt.decode(tokend);
  //   console.log(`tokend:  ${tokend}`);

  return (
    <FormProvider>
      <UserDataProvider>
        <SessionWrapper>
          <html lang="en">
            <body className={`  bg-[#FFFCF9] text-black antialiased`}>
              <Header
                user={token ? true : false}
                tokenData={data}
                data={userData}
              />
              {children}
              <Footer />
              <Toaster />
            </body>
          </html>
        </SessionWrapper>
      </UserDataProvider>
    </FormProvider>
  );
}

// export async function getStaticProps() {
//   try {

//     const res = await axios.get('http://localhost:3000/api/user/details');
//     const data = res.data;

//     console.log(data);

//     return {
//       props: { data },
//       revalidate: 5,
//     };
//   } catch (error) {
//     console.error('Error fetching static content', error);
//     return {
//       props: {
//         data: null,
//       },
//     };
//   }
// }
